[package]
name = "skill_builder_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
msgbox = "0.7.0"
once_cell = "1.21.3"
rdev = "0.5.3"
rustautogui = "2.5.0"
slint = "1.14.1"
winapi = { version = "0.3.9", features = ["winuser"] }
